import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';
import Contact from '../components/Contact';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Treiger Photos</title>
        <meta
          name="Sites de fotos do fotógrafo Adrian Treiger"
          content="Generated by create next app"
        />
        <link rel="icon" href="/adrian.ico" />
      </Head>
      <Hero
        heading="Capture sonhos"
        message="Eternizando momentos através da minha lente... 📸"
      />
      <Slider slides={SliderData} />
      <Instagram />
      <Footer />
    </div>
  );
}
